config/routes.rb
Rails.application.routes.draw do
  get 'home/about' =>'homes#about'
  get 'users' => 'users#index'
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
  root :to => "homes#top"
  get '' => 'homes#top'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  validates :introduction, length: { maximum: 50}

  attachment :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, presence: true

    has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.


  # If you have extra params to permit, append them to the sanitizer.


  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]
    protected
    def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end
    def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
    end

    def after_update_path_for(resource)
        user_path(id: current_user.id)
    end

    def update_resource(resource, params)
        resource.update_without_password(params)
    end



end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  # If you have extra params to permit, append them to the sanitizer.

  #  protected
  #  def configure_sign_in_params
  #      devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  #  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
    @users = User.all
  	@book = Book.new
    @books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
    if current_user !=  @user
      redirect_to user_path(current_user)
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def update
        user = User.find(params[:id])
        if user.update(list_params)
          redirect_to user_path(user.id),notice: " successfully update."
        else
          @user = User.find(params[:id])
          flash[:notice] = "error"
          render :edit
        end
    end

    def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def list_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
     user == current_user
  end

end

app/views/users/edit.html.erb
<div class="container">


    <h2>User info </h2>
    <%= form_for(@user) do |f| %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label :profile_image %>
    <%= f.attachment_field :profile_image %>

  <div class="field">
    <%= f.label :Introduction %><br />
    <%= f.text_field :introduction, autofocus: true %>
  </div>



  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="body">
<div class="container">
<div class="row">

<div class="col-xs-3">
  <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: 'no_image.png',size: '100x100' %>



      <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <td><%= current_user.name %></td>
            </tr>

            <tr>
              <th>introduction</th>
              <td><%= current_user.introduction%></td>
            </tr>
          </tbody>
          <td>
                   <% @user ||= current_user %>
                        <a href="<%= following_user_path(@user) %>">
                          <strong id="following" class="stat">
                            <%= @user.followings.count %>
                          </strong>
                          following
                        </a>
                      </div>
                    </td>
                  </tr>
                    <td>
                        <a href="<%= followers_user_path(@user) %>">
                          <strong id="followers" class="stat">
                            <%= @user.followers.count %>
                          </strong>
                          followers
                        </a>
                  </td>

      </table>

  <div class="row">
    <%= link_to edit_user_path(current_user) do %>
    <button type="button" class="col-xs-12 btn btn-default"><i class="glyphicon glyphicon-wrench" ></i></button>
    <% end %>

         <h1>New book</h1>
             <%= form_for(@book, url: '/books') do |f| %>

         <h4>Title</h4>
             <%= f.text_field :title %>

         <h4>Opinion</h4>
             <%= f.text_area :body %>

         <%= f.submit 'Create Book' %>

         <% end %>
  </div>
</div>










<div class="col-xs-9">
    <h2>Users</h2>

<table class="table table-hover table-inverse">

  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg' ,fallback: 'no_image.png',size: '40x40'%></td>

        <td><%= user.name %></td>

        <td>
          <% unless current_user?(user) %>
            <% if current_user.following?(user) %>
                <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
                  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
                <% end %>
            <% else %>
                <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
                  <div><%= f.hidden_field :following_id %></div>
                  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
                <% end %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>


</table>

</div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="body">
  <div class="container">
    <% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <li>error</li>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: 'no_image.png',size: '100x100' %></th>

            <table class="table">
                <tbody>
                  <tr></tr>
                  <tr>
                    <th>name</th>
                    <td><%= @user.name %></td>
                  </tr>

                  <tr>
                    <th>introduction</th>
                    <td><%= @user.introduction %></td>
                  </tr>
                  <tr>
                  <td>
                   <% @user ||= current_user %>
                        <a href="<%= following_user_path(@user) %>">
                          <strong id="following" class="stat">
                            <%= @user.followings.count %>
                          </strong>
                          following
                        </a>
                      </div>
                    </td>
                  </tr>
                    <td>
                        <a href="<%= followers_user_path(@user) %>">
                          <strong id="followers" class="stat">
                            <%= @user.followers.count %>
                          </strong>
                          followers
                        </a>
                  </td>


                </tbody>



            </table>
            <% unless current_user?(@user) %>
                    <% if current_user.following?(@user) %>
              <%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
                  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
                <% end %>
                <% else %>
                <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
                  <div><%= f.hidden_field :following_id %></div>
                  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
                <% end %>
                <% end %>
<% end %>

          <div class="row">
            <% if @user == current_user %>
              <%= link_to edit_user_path(current_user) do %>
                <button type="button" class="col-xs-12 btn btn-default"><i class="glyphicon glyphicon-wrench" ></i></button>
              <% end %>
            <% else %>
              <%= link_to user_path(current_user) do %>
                <button type="button" class="col-xs-12 btn btn-default"><i class="glyphicon glyphicon-wrench" ></i></button>
              <% end %>
            <% end %>

            <div class="col-xs-12">
              <h1>New book</h1>
                 <%= form_for(@book, url: '/books') do |f| %>

              <h4>Title</h4>
                 <%= f.text_field :title %>

              <h4>Opinion</h4>
                 <%= f.text_area :body %>

                  <button type="submit" class="col-xs-12 btn btn-primary">Create Book</button>
            <% end %>
            </div>
          </div>
      </div>

      <div class="col-xs-9">
          <h2>Bookss</h2>

           <table class="table table-hover table-inverse">

           <thead>
              <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              </tr>
           </thead>
           <tbody>
              <% @books.each do |book| %>
                    <tr>
                      <th>
                        <%= link_to user_path(book.user_id) do %>
                        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'pin',fallback: 'no_image.png',size: '40x40' %>
                        <% end %>
                      </th>
                      <td><%= link_to  book.title , book_path(book.id) %></td>
                      <td><%= book.body %></td>
                                <td>
                <% if book.favorited_by?(current_user) %>
                  <li>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
                      <%= book.favorites.count %>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                      <%= book.favorites.count %>
                    <% end %>
                  </li>
                <% end %>
              </td>
                        <td>
            <i class="fa fa-comment"></i>
            コメント数：<%= book.book_comments.count %></a>
          </td>


                    </tr>
               <% end %>
            </tbody>
          </table>

      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
  <% @user.followings.each do |user| %>
	<table>
		<tr>
		  <td>  <%= user.name %> </td>
		  <td><%= link_to '詳細', user_path(user) %></td>
		</tr>

	</table>
  <% end %>
</div>

app/views/users/show_follower.html.erb
<div class="container">
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>
</div>