config/routes.rb
Rails.application.routes.draw do
  get 'home/about' =>'homes#about'
  get 'users' => 'users#index'
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
  root :to => "homes#top"
  get '' => 'homes#top'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

    validates :title, presence: true

    validates :body, presence: true, length: { maximum: 200 }

    has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end

    has_many :book_comments, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @bookn = Book.new
    @books = Book.all


  end

  def show
    @book = Book.find(params[:id])
    @bookn = Book.new
    @bookc = BookComment.new
  end

  def new
  	@book = Book.new
  end

  def edit
     @book = Book.find(params[:id])
     if current_user !=  @book.user
      redirect_to books_path
     end
  end

  def create
    @book = Book.new(list_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id) ,notice: "You have creatad book successfully."
    else
      @users = User.all
      @books = Book.all
      render :index
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(list_params)
    redirect_to book_path(book.id),notice: " successfully update."
    else
      @book = Book.find(params[:id])
      flash[:notice] = "error"
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private
  def list_params
      params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="body">
<div class="container">

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>
			    <h4>Title</h4>
			    <%= f.text_field :title,class: "col-md-12" %>
			    <h4>Body</h4>
			    <%= f.text_area :body %>
			    <%= f.submit 'Update Book',class: 'btn btn-primary col-md-12' %>
			<% end %>

		    <%= link_to "Show",book_path %>
		    <%= link_to "Back", books_path %>

		</div>
	</div>
</div>
</div>

app/views/books/index.html.erb
<div class="body">
<div class="container">

    <%=  notice %>
    <% if @bookn.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <li>error</li>
      <% @bookn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">



   <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg' ,fallback: 'no_image.png',size: '100x100'%>


          <table class="table">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <td><%= current_user.name %></td>
                </tr>

                <tr>
                  <th>introduction</th>
                  <td><%= current_user.introduction %></td>
                </tr>
              </tbody>
              <td>
                   <% @user ||= current_user %>
                        <a href="<%= following_user_path(@user) %>">
                          <strong id="following" class="stat">
                            <%= @user.followings.count %>
                          </strong>
                          following
                        </a>
                      </div>
                    </td>
                  </tr>
                    <td>
                        <a href="<%= followers_user_path(@user) %>">
                          <strong id="followers" class="stat">
                            <%= @user.followers.count %>
                          </strong>
                          followers
                        </a>
                  </td>

          </table>

   <div class="row">
      <%= link_to edit_user_path(current_user) do %>
      <button type="button" class="col-xs-12 btn btn-default"><i class="glyphicon glyphicon-wrench" ></i></button>
      <% end %>

           <h1>New book</h1>
               <%= form_for(@bookn, url: '/books') do |f| %>

           <h4>Title</h4>
               <%= f.text_field :title %>

           <h4>Opinion</h4>
               <%= f.text_area :body %>

           <%= f.submit 'Create Book' %>

           <% end %>
   </div>
   </div>




<div class="col-xs-9">
    <h2>Books</h2>

       <table class="table table-hover table-inverse">

       <thead>
          <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          </tr>
       </thead>
<% @books.each do |book| %>

       <tbody>
          <tr>
          <th>
            <%= link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: 'no_image.png',size: '40x40' %>
            <% end %>
            </th>
          <td><%= link_to  book.title , book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>
                <% if book.favorited_by?(current_user) %>
                  <li>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
                      <%= book.favorites.count %>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                      <%= book.favorites.count %>
                    <% end %>
                  </li>
                <% end %>
              </td>
                        <td>
            <i class="fa fa-comment"></i>
            コメント数：<%= book.book_comments.count %></a>
          </td>

        </tr>
   <% end %>
    </tbody>
</table>


</div>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>
</div>

app/views/books/show.html.erb
<div class="body">
  <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <li>error</li>
           <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
      </ul>
    </div>
  <% end %>
  <%= notice %>

<div class="container">
<div class="row">

   <div class="col-xs-3">
      <h2>User info</h2>
         <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg' ,fallback: 'no_image.png',size: '100x100'%>

        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <td><%= @book.user.name %></td>
            </tr>

            <tr>
              <th>introduction</th>
              <td><%= @book.user.introduction %></td>
            </tr>
          </tbody>
          <td>
                   <% @user ||= current_user %>
                        <a href="<%= following_user_path(@user) %>">
                          <strong id="following" class="stat">
                            <%= @user.followings.count %>
                          </strong>
                          following
                        </a>
                      </div>
                    </td>
                  </tr>
                    <td>
                        <a href="<%= followers_user_path(@user) %>">
                          <strong id="followers" class="stat">
                            <%= @user.followers.count %>
                          </strong>
                          followers
                        </a>
                  </td>

        </table>

       <div class="row">
         <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user" href="/users/edit"></a>

               <h1>New book</h1>
                   <%= form_for(@bookn, url: '/books') do |f| %>

               <h4>Title</h4>
                   <%= f.text_field :title %>

               <h4>Opinion</h4>
                   <%= f.text_area :body %>

               <%= f.submit 'Create Book' %>

               <% end %>
       </div>
   </div>




<div class="col-xs-9">
		<h2>Book detail</h2>

       <table class="table table-hover table-inverse">

       <thead>
          <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          </tr>
       </thead>


       <tbody>
          <tr>
          <th>
            <%= link_to user_path(@book.user_id) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: 'no_image.png',size: '40x40' %>
              <% end %>
            </th>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <!-- favorite -->
<td>
                <% if @book.favorited_by?(current_user) %>
                  <li>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
                      <%= @book.favorites.count %>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                      <%= @book.favorites.count %>
                    <% end %>
                  </li>
                <% end %>
              </td>


          <td>
            <i class="fa fa-comment"></i>
            コメント数：<%= @book.book_comments.count %></a>
          </td>

          <td>
            <% if @book.user == current_user %>
             <%= link_to "Edit",edit_book_path(@book.id) %>
            <% end %>
          </td>
          <td>
            <% if @book.user == current_user %>
              <%= link_to "Destroy", book_path, method: :delete %>
            <% end %>
          </td>
        </tr>
        <td><%= link_to @book.user.name , user_path(@book.user.id) %></td>

    </tbody>
<!-- favorite -->

</table>
<!--comment -->
<!-- <form class="mt-20"> -->
<%= form_for [@book, @bookc] do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
        </div>
    </div>
    <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
<!-- </form> -->


<div class="comment-list bt style-2" id="comments">
    <div class="float-wrapper">
        <h2 class="comment-count"><%= @book.book_comments.count %>件コメント</h2>
    </div>
 <ol>
    <% @book.book_comments.each do |book_comment| %>
        <li class="comment">
            <div class="comment-body bb">
                <div class="comment-avatar">
                    <div class="avatar">
      <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback: 'no_image.png',size: '60x60'%>
                    </div>
                </div>
                <div class="comment-text">
                    <div class="comment-author clearfix">
                        <a href="#" class="link-author"><%= book_comment.user.name %></a>
                        <span class="comment-meta">
                          <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
                        </span>
                    </div>
                    <div class="comment-entry"><%= book_comment.comment %></div>
                </div>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(@book.id,book_comment.id), method: :delete %>
            <% end %>

            </div>
        </li>
    <% end %>




  </ol>

 <!-- コメント -->

</div>
</div>
</div>
</div>