config/routes.rb
Rails.application.routes.draw do
  get 'home/about' =>'homes#about'
  get 'users' => 'users#index'
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
  root :to => "homes#top"
  get '' => 'homes#top'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

    validates :title, presence: true

    validates :body, presence: true, length: { maximum: 200 }

    has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end

    has_many :book_comments, dependent: :destroy
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
    belongs_to :book

    validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	 belongs_to :following, class_name: "User"
 validates :following_id, presence: true
belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  validates :introduction, length: { maximum: 50}

  attachment :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, presence: true

    has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:password])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
end

  def destroy
    comment = BookComment.find(params[:id])
    comment.destroy
    flash[:success] = '投稿へのコメントを削除しました。'
    redirect_back(fallback_location: root_path)
  end


private
def book_comment_params
    params.require(:book_comment).permit(:comment)
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @bookn = Book.new
    @books = Book.all


  end

  def show
    @book = Book.find(params[:id])
    @bookn = Book.new
    @bookc = BookComment.new
  end

  def new
  	@book = Book.new
  end

  def edit
     @book = Book.find(params[:id])
     if current_user !=  @book.user
      redirect_to books_path
     end
  end

  def create
    @book = Book.new(list_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id) ,notice: "You have creatad book successfully."
    else
      @users = User.all
      @books = Book.all
      render :index
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(list_params)
    redirect_to book_path(book.id),notice: " successfully update."
    else
      @book = Book.find(params[:id])
      flash[:notice] = "error"
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private
  def list_params
      params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back(fallback_location: root_path)    end

    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
    end

    def about
 	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
    @users = User.all
  	@book = Book.new
    @books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
    if current_user !=  @user
      redirect_to user_path(current_user)
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def update
        user = User.find(params[:id])
        if user.update(list_params)
          redirect_to user_path(user.id),notice: " successfully update."
        else
          @user = User.find(params[:id])
          flash[:notice] = "error"
          render :edit
        end
    end

    def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def list_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
     user == current_user
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to " Home", user_path(current_user.id),class: "glyphicon glyphicon-home" %>
              </li>
              <li>
                <%= link_to " Users", users_path ,class: "glyphicon glyphicon-user" %>
              </li>
              <li>
                <%= link_to " Books", books_path ,class: "glyphicon glyphicon-book" %>
              </li>
              <li>
                <%= link_to " logout", destroy_user_session_path, method: :delete ,class: "glyphicon glyphicon-log-out"%>
              </li>
            <% else %>
              <li>
                <%= link_to " Home", root_path ,class: "glyphicon glyphicon-home" %>
              </li>
              <li>
                <%= link_to " About", home_about_path ,class: "glyphicon glyphicon-link about" %>
              </li>
              <li>
                <%= link_to " sign up",new_user_registration_path ,class: "glyphicon glyphicon-edit" %>
              </li>
              <li>
                <%= link_to " login",new_user_session_path ,class: "glyphicon glyphicon-log-in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <% if flash[:notice] %>
      <%=  flash[:notice] %>
    <% end %>


    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p> CopyRight Infratop.inc </p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>